### PR TITLE
SJHOSPICERAFFLE-JULY-23-WINNER

### PR DESCRIPTION
**Pull request by vijay99rathod**

### CODE REVIEW

**Review by ecerrudo — CHANGES_REQUESTED** [review]
@vijay99rathod add a dash between G and 2192393. Draw Date is wrong, should be July 22, not 23.

**Review by vijay99rathod — COMMENTED** [review]
Hi @ecerrudo please review updated changes, Thanks!

**Review by ecerrudo — COMMENTED** [review]
@vijay99rathod good to go now.

**Review by ecerrudo — APPROVED** [review]
@vijay99rathod good to go.

**Pull request merged**
